CREATE TABLE IF NOT EXISTS url_bookmarks.tags(
       id INT AUTO_INCREMENT,
       title NOT NULL VARCHAR(50),
       description VARCHAR(100) DEFAULT '',
       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
